version : "3.8" 
services : 
    user-service: 
        container_name : user-service-mongo
        restart : always 
        build : . 
        ports : 
          - '5200:5200' 
        links: 
          - mongo
          -  euroka-server 
    mongo:
        container_name : mongo
        image : mongo
        ports: 
          - '27017:27017'
    euroka-server:
       container_name: euroka-server
       image: "euroka"
       ports:
         - "8761:8761"
           
  
       